name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Shaleen Garg
        author_email: shaleengarg.in@gmail.com
        message: "Your commit madf"
        add: "pappu"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
